service: serverless-pay
frameworkVersion: '2'
useDotenv: true
disabledDeprecations:
  - '*'

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
    packager: 'yarn'
    excludeFiles: src/**/*.test.js

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-2

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: '{any+}'
          method: any
          cors: true
